### 予想
breakしてループから抜けたあとに、finallyでcontinueを実行するので、TypeErrorになる。

### 結果
5が出力された。